import torch.nn as nn
import numpy as np
import torch

tensorA = torch.tensor([4, 2, 7])
print(tensorA.dtype)
tensorT = torch.Tensor([4,2,7])
print(tensorT.dtype)
tensorA_float = torch.tensor([4,2,7], dtype = torch.float32)


tensorA_softmax = nn.functional.softmax(tensorA_float, dim = 0)

tensorB = torch.tensor([4,2], dtype = torch.float32)
tensorB_softmax = nn.functional.softmax(tensorB)
#tensorB_logit = tensorB

print("tensorB_softmax : ", tensorB_softmax)
#print("tensorB_logit : ", tensorB_logit)


In [ ]:
tensorA = torch.randn(5,10)
mask = torch.tensor([0,1])
mm = torch.nn.Conv2d(3,3, 3)

In [ ]:
def laplacian_loss(output, gt, dist_type="l2"):
    """
    Computes the laplacian of the input and output grid and defines
    regression loss.
    :param output: predicted control points grid. Makes sure the orientation/
    permutation of this output grid matches with the ground truth orientation.
    This is done by finding the least cost orientation during training.
    :param gt: gt control points grid.
    """
    batch_size, grid_size, grid_size, input_channels = gt.shape
    filter = ([[[0.0, 0.25, 0.0], [0.25, -1.0, 0.25], [0.0, 0.25, 0.0]],
               [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
               [[0, 0, 0], [0, 0, 0], [0, 0, 0]]])
    filter = np.stack([filter, np.roll(filter, 1, 0), np.roll(filter, 2, 0)])

    filter = -np.array(filter, dtype=np.float32)
    filter = Variable(torch.from_numpy(filter)).cuda()

    laplacian_output = F.conv2d(output.permute(0, 3, 1, 2), filter, padding=1)
    laplacian_input = F.conv2d(gt.permute(0, 3, 1, 2), filter, padding=1)
    if dist_type == "l2":
        dist = (laplacian_output - laplacian_input) ** 2
    elif dist_type == "l1":
        dist = torch.abs(laplacian_output - laplacian_input)
    dist = torch.sum(dist, 1)
    dist = torch.mean(dist)
    return dist

In [8]:
import torch

testA = torch.rand(2,3)
print(testA)
print(testA.size())
print(testA.unsqueeze(0))
print(testA.size())
torch.unsqueeze(testA, 0)
print(testA.size())

tensor([[0.7598, 0.0236, 0.2425],
        [0.2166, 0.6806, 0.1716]])
torch.Size([2, 3])
tensor([[[0.7598, 0.0236, 0.2425],
         [0.2166, 0.6806, 0.1716]]])
torch.Size([2, 3])
torch.Size([2, 3])


In [9]:
testB = torch.tensor([[2,3,4], [6,8,9]])
testC = torch.tensor([[1.2, 1.4, 2.1], [3.2, -0.7, 4.4]])

print(testB * testC)

tensor([[ 2.4000,  4.2000,  8.4000],
        [19.2000, -5.6000, 39.6000]])


In [10]:
print(testB) # 2,3
print(testB[..., 2])

tensor([[2, 3, 4],
        [6, 8, 9]])
tensor([4, 9])


In [12]:
testD = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(testD)
print(testD[..., 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([3, 6, 9])


In [26]:
print(testD[...,2])
print(testD[...,2].unsqueeze(1).size())
print(testD[...,2].unsqueeze(1).expand(-1,4) )

tensor([3, 6, 9])
torch.Size([3, 1])
tensor([[3, 3, 3, 3],
        [6, 6, 6, 6],
        [9, 9, 9, 9]])


In [37]:
testE = torch.rand(3,5)
print(testE)
print(testE.size())
temp = torch.ones(3)
print(temp)
sampleMatrix = torch.diag(temp)

sampleMatrix = torch.cat((sampleMatrix, torch.zeros(2,3) ), dim = 0)

print("sampleMatrix : \n", sampleMatrix)
res = testE @ sampleMatrix
print(res)



tensor([[0.9745, 0.6390, 0.9687, 0.1459, 0.3563],
        [0.7651, 0.4066, 0.8709, 0.9489, 0.8819],
        [0.7513, 0.7403, 0.4461, 0.9847, 0.6397]])
torch.Size([3, 5])
tensor([1., 1., 1.])
sampleMatrix : 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9745, 0.6390, 0.9687],
        [0.7651, 0.4066, 0.8709],
        [0.7513, 0.7403, 0.4461]])


In [38]:
testB = torch.cat((torch.eye(3), torch.zeros(2,3)), dim = 0)
print(testB)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
import torch
import numpy

outputMasked = torch.randn(6,9) *3
print("This is outputMasked : \n", outputMasked)
num_cpA = 1
num_cpB = 2
wB = outputMasked[..., (num_cpA*4 + num_cpB) : ] #
print("wB.size() : ", wB.size())
print("wB : ", wB)
wB2 = outputMasked[..., 3]
print(wB2)

This is outputMasked : 
 tensor([[-2.8353,  4.3820,  4.4387, -6.2966,  4.6793,  0.7990,  4.3285,  1.2427,
          0.3055],
        [ 3.2232, -3.2014, -3.2920,  4.9047,  0.0204, -3.5923, -4.5770,  1.8010,
          2.1115],
        [-6.7608, -4.8983, -0.9471, -4.7260, -4.2014,  0.5766, -2.6480,  3.9963,
         -1.2265],
        [ 0.8728,  0.9764,  1.6653, -2.0932, -1.2026,  2.9354, -4.7481,  1.1030,
          1.9615],
        [-0.0774,  4.0131, -5.1935,  3.8026, -0.7173,  5.4148,  0.7700, -1.3352,
         -1.0732],
        [ 4.5388,  0.6936,  2.3029, -1.9176, -0.8837, -0.2536, -2.0416, -1.4104,
          5.8195]])
wB.size() :  torch.Size([6, 3])
wB :  tensor([[ 4.3285,  1.2427,  0.3055],
        [-4.5770,  1.8010,  2.1115],
        [-2.6480,  3.9963, -1.2265],
        [-4.7481,  1.1030,  1.9615],
        [ 0.7700, -1.3352, -1.0732],
        [-2.0416, -1.4104,  5.8195]])
tensor([-6.2966,  4.9047, -4.7260, -2.0932,  3.8026, -1.9176])


In [9]:
example = torch.tensor([[1,2,3], [4,5,6]])
print(example[..., 2])

tensor([3, 6])


In [1]:
import torch

tA = torch.tensor([[1,0], [1,2]])
for i in range(2):
    for j in range(2):
        if tA[i][j].item() == 1:
            print(tA[i][j])
        if tA[i][j] == 1:
            print(tA[i][j])
        if tA[i][j].item() == 1:
            print(tA[i][j].item())


tensor(1)
tensor(1)
1
tensor(1)
tensor(1)
1


In [29]:
# torch.nn.functional.upsample(example, scale_factor = 2, mode='nearest')
m = example.repeat(2,2)
tor = torch.zeros_like(example)
# print(tor)
# print(example[..., 1:])
n = torch.cat((torch.zeros_like(example[..., :1]),example[..., 1:]), dim = 1).repeat(2,2)
print(m)
print(n)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])
tensor([[0, 2, 3, 0, 2, 3],
        [0, 5, 6, 0, 5, 6],
        [0, 2, 3, 0, 2, 3],
        [0, 5, 6, 0, 5, 6]])


In [52]:

example3 = torch.tensor(example.unsqueeze(0), dtype = torch.float)
m = torch.nn.functional.upsample(example3, scale_factor = 4, mode = 'nearest')
print(m)
print(example)


tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.],
         [4., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6.]]])
tensor([[1, 2, 3],
        [4, 5, 6]])


/home/cloudest/anaconda3/envs/parsenet/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [53]:
print(m.squeeze(0))

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.],
        [4., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6.]])


In [59]:
print(torch.sum(example[..., 0])

tensor(5)

In [60]:
ex1 = torch.tensor([[1,2,3],[4,5,6]])
ex2 = torch.rand(2,3)
print(ex1 + ex2)

tensor([[1.4685, 2.6025, 3.6450],
        [4.4763, 5.8329, 6.6538]])


In [61]:
AProb = 0.7
BProb = 0.3
print("AProb : {0} BProb : {1}".format(AProb, BProb))

AProb : 0.7 BProb : 0.3


In [82]:
ex1 = ex1 = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)
print("ex1 : \n", ex1)
ex2 = torch.nn.functional.upsample(ex1.unsqueeze(0), scale_factor = 4, mode = 'nearest')
ex3 = torch.flatten(ex1)
zero1 = torch.zeros_like(ex3)
print("ex2 : \n", ex2)
print("ex3 : \n", ex3)
ex3Zero1 = torch.cat((zero1, ex3), dim = 0)
print("ex3Zero1 : \n", ex3Zero1)
ex3Zero1Reshaped = ex3Zero1.view(2,6)
print(ex3Zero1Reshaped)

ex1 : 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
ex2 : 
 tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.],
         [4., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6.]]])
ex3 : 
 tensor([1., 2., 3., 4., 5., 6.])
ex3Zero1 : 
 tensor([0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6.])
tensor([[0., 0., 0., 0., 0., 0.],
        [1., 2., 3., 4., 5., 6.]])


In [97]:
ex4 = ex1.unsqueeze(2)
#print(ex4)
ex5 = torch.zeros_like(ex4)
#print(ex5)

print(torch.cat((ex4,ex5), dim = 0))
print(torch.cat((ex4,ex5), dim = 1))
z3 = torch.cat((ex4,ex5), dim = 2)
print(z3)
print(z3.view(3,4))

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
tensor([[[1.],
         [2.],
         [3.],
         [0.],
         [0.],
         [0.]],

        [[4.],
         [5.],
         [6.],
         [0.],
         [0.],
         [0.]]])
tensor([[[1., 0.],
         [2., 0.],
         [3., 0.]],

        [[4., 0.],
         [5., 0.],
         [6., 0.]]])
tensor([[1., 0., 2., 0.],
        [3., 0., 4., 0.],
        [5., 0., 6., 0.]])


In [1]:
import torch

ex1 = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)
print("ex1 : \n", ex1)
ex2 = ex1.unsqueeze(2)
print("ex2 : \n", ex2)
zeros = torch.zeros_like(ex2)
ex2Zero = torch.cat((ex2, zeros), dim = 2)
print("ex2Zero : \n", ex2Zero)
ex3 = ex2Zero.view(3,4)
print("ex3 : \n", ex3)

zeros3 = torch.zeros((ex2.shape[0], ex2.shape[1], ex2.shape[2]*3))
ex2Zero3 = torch.cat((ex2, zeros3), dim = 2)
print("ex2Zero3 : \n", ex2Zero3)
ex4 = ex2Zero3.view(3,8)
print("ex4 : \n", ex4)

def zeroSamplingby4(inp):
    inpUnsqzd = inp.unsqueeze(2)
    zeros = torch.zeros(inpUnsqzd.shape[0], inpUnsqzd.shape[1], inpUnsqzd.shape[2]*3)
    inpZerosCat = torch.cat((inpUnsqzd, zeros), dim = 2)
    out = inpZerosCat.view(-1,inp.shape[1]*4)
    return out
print("zeroSamplingby4(ex1) : ", zeroSamplingby4(ex1))

ex1 : 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
ex2 : 
 tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])
ex2Zero : 
 tensor([[[1., 0.],
         [2., 0.],
         [3., 0.]],

        [[4., 0.],
         [5., 0.],
         [6., 0.]]])
ex3 : 
 tensor([[1., 0., 2., 0.],
        [3., 0., 4., 0.],
        [5., 0., 6., 0.]])
ex2Zero3 : 
 tensor([[[1., 0., 0., 0.],
         [2., 0., 0., 0.],
         [3., 0., 0., 0.]],

        [[4., 0., 0., 0.],
         [5., 0., 0., 0.],
         [6., 0., 0., 0.]]])
ex4 : 
 tensor([[1., 0., 0., 0., 2., 0., 0., 0.],
        [3., 0., 0., 0., 4., 0., 0., 0.],
        [5., 0., 0., 0., 6., 0., 0., 0.]])
zeroSamplingby4(ex1) :  tensor([[1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0.],
        [4., 0., 0., 0., 5., 0., 0., 0., 6., 0., 0., 0.]])


In [6]:
print(ex1[..., :2])
print(ex1[..., 1:])

tensor([[1., 2.],
        [4., 5.]])
tensor([[2., 3.],
        [5., 6.]])


In [9]:
ex6 = torch.randint(50, (6,4)) * 0.1
print(ex6.dtype)
print(ex6)
ex6Sum = torch.sum(ex6, dim = 0)
print(ex6Sum)
print(torch.argmax(ex6Sum))

torch.float32
tensor([[0.8000, 2.1000, 3.4000, 2.7000],
        [0.4000, 0.3000, 2.8000, 1.3000],
        [4.3000, 2.3000, 3.8000, 1.8000],
        [4.7000, 2.4000, 1.5000, 3.4000],
        [1.7000, 3.2000, 1.3000, 3.3000],
        [1.3000, 3.1000, 0.4000, 1.8000]])
tensor([13.2000, 13.4000, 13.2000, 14.3000])
tensor(3)


In [11]:
ex7 = [1,2,3,4]
# ls = [type(item) for item in ex7]
# print(ls)
ex7_str = ['1','2','3','4']
ex7_strToList = map(int, ex7_str)
print(type(ex7_strToList))
len
print([type(item) for item in ex7_strToList])

<class 'map'>
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


In [19]:
import torch

for e in range(5):
    probSumTrain = torch.zeros(5, dtype=torch.float32)
#     print("empty probSumTrain : ", probSumTrain)
    for i in range(7):
        training = torch.tensor([1,2,3,4,5])*0.1
        probSumTrain += training
    print(probSumTrain / 0.4)

tensor([1.7500, 3.5000, 5.2500, 7.0000, 8.7500])
tensor([1.7500, 3.5000, 5.2500, 7.0000, 8.7500])
tensor([1.7500, 3.5000, 5.2500, 7.0000, 8.7500])
tensor([1.7500, 3.5000, 5.2500, 7.0000, 8.7500])
tensor([1.7500, 3.5000, 5.2500, 7.0000, 8.7500])


In [21]:
print(probSumTrain[0].item())

0.7000000476837158


In [2]:
listA = [1,2,3,4,5]

list1 = [[] for item in range(len(listA))]
print(list1)

[[], [], [], [], []]


In [5]:
import torch
x = torch.rand(5,4)
print('x : \n', x)
loc = torch.ByteTensor([0,1,0,0,1])
print('loc : \n', loc)
y = x[loc]
print('y: \n', y)


x : 
 tensor([[0.9904, 0.8120, 0.3333, 0.9441],
        [0.3408, 0.6465, 0.9966, 0.7904],
        [0.6436, 0.0542, 0.3934, 0.6916],
        [0.3230, 0.3169, 0.6989, 0.8590],
        [0.9851, 0.7184, 0.4080, 0.1900]])
loc : 
 tensor([0, 1, 0, 0, 1], dtype=torch.uint8)
y: 
 tensor([[0.3408, 0.6465, 0.9966, 0.7904],
        [0.9851, 0.7184, 0.4080, 0.1900]])


/home/cloudest/anaconda3/envs/parsenet/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:25.)
  


In [87]:
x2 = torch.tensor([[0.7, 0.2, 0.1, 0.0, 0.0],
                   [0.3, 0.4, 0.1, 0.1, 0.1],
                   [0.2, 0.3, 0.4, 0.0, 0.1],
                   [0.1, 0.8, 0.1, 0.0, 0.0],
                   [0.0, 0.7, 0.3, 0.0, 0.0],
                   [0.2, 0.4, 0.1, 0.3, 0.0],
                   [0.3, 0.1, 0.5, 0.0, 0.0],
                   [0.2, 0.7, 0.0, 0.1, 0.0],
                   [0.1, 0.1, 0.2, 0.4, 0.2],
                   [0.0, 1.0, 0.0, 0.0, 0.0]])
xArgmax = torch.argmax(x2, dim = 1)
print(xArgmax) # argmax는 두 원소 값이 같으면 index가 먼저인 것, 즉 작은 것을 반환한다.
print(x2.device)

tensor([0, 1, 2, 1, 1, 1, 2, 1, 3, 1])
cpu


In [78]:
##### for network 1 #####
print(x2[torch.ByteTensor([0,1,0,1,1,1,0,0,0,1])]) # This is what I want
##### OR #####
x2Max, indices = torch.max(x2, dim =1)
print(indices)
print(x2[indices == 1])
print(x2[indices == 4])

print(x2[[1,3,4,5,7,9]])
print(indices == 1)


tensor([[0.3000, 0.4000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.8000, 0.1000, 0.0000, 0.0000],
        [0.0000, 0.7000, 0.3000, 0.0000, 0.0000],
        [0.2000, 0.4000, 0.1000, 0.3000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000]])
tensor([0, 1, 2, 1, 1, 1, 2, 1, 3, 1])
tensor([[0.3000, 0.4000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.8000, 0.1000, 0.0000, 0.0000],
        [0.0000, 0.7000, 0.3000, 0.0000, 0.0000],
        [0.2000, 0.4000, 0.1000, 0.3000, 0.0000],
        [0.2000, 0.7000, 0.0000, 0.1000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000]])
tensor([], size=(0, 5))
tensor([[0.3000, 0.4000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.8000, 0.1000, 0.0000, 0.0000],
        [0.0000, 0.7000, 0.3000, 0.0000, 0.0000],
        [0.2000, 0.4000, 0.1000, 0.3000, 0.0000],
        [0.2000, 0.7000, 0.0000, 0.1000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000]])
tensor([False,  True, False,  True,  True,  True, False,  True, False,  True])


/home/cloudest/anaconda3/envs/parsenet/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:25.)
  


In [79]:
x2List = [[0.7, 0.2, 0.1, 0.0, 0.0],
                   [0.3, 0.4, 0.1, 0.1, 0.1],
                   [0.2, 0.3, 0.4, 0.0, 0.1],
                   [0.1, 0.8, 0.1, 0.0, 0.0],
                   [0.0, 0.7, 0.3, 0.0, 0.0],
                   [0.2, 0.4, 0.1, 0.3, 0.0],
                   [0.3, 0.1, 0.5, 0.0, 0.0],
                   [0.2, 0.7, 0.0, 0.1, 0.0],
                   [0.1, 0.1, 0.2, 0.4, 0.2],
                   [0.0, 1.0, 0.0, 0.0, 0.0]]

In [81]:
print(torch.tensor(x2List)
      [indices == 1])

tensor([[0.3000, 0.4000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.8000, 0.1000, 0.0000, 0.0000],
        [0.0000, 0.7000, 0.3000, 0.0000, 0.0000],
        [0.2000, 0.4000, 0.1000, 0.3000, 0.0000],
        [0.2000, 0.7000, 0.0000, 0.1000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000]])


In [82]:
import numpy as np

x2Num = np.array(x2)
print(x2[indices == 1])

tensor([[0.3000, 0.4000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.8000, 0.1000, 0.0000, 0.0000],
        [0.0000, 0.7000, 0.3000, 0.0000, 0.0000],
        [0.2000, 0.4000, 0.1000, 0.3000, 0.0000],
        [0.2000, 0.7000, 0.0000, 0.1000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000]])


In [83]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(1, 2)

abStack = np.stack((a,b), 0)

print(abStack)


ValueError: all input arrays must have the same shape

In [100]:
import numpy as np
import torch

scales = [[[0.0683, 0.9202, 1.0961]], [[0.4122, 0.9997, 0.7656]],[[0.1657, 0.3025, 0.9997]], 
          [[0.0117, 0.8207, 0.653 ]], [[0.193 , 0.4365, 1.0564]],[[0.0066, 0.1864, 0.9978]], 
          [[0.1757, 1.0406, 0.7988]], [[0.0023, 0.9993, 0.0222]], [[0.0091, 0.4855, 1.0033]]]
''', array([[0.1623, 0.6097, 0.7742]]), array([[0.0753, 0.5742, 0.9992]]), array([[0.4752, 0.8525, 1.0026]]), array([[0.1385, 0.9416, 0.6873]]), array([[1.9151e-08, 5.5213e-02, 9.9936e-01]]), array([[5.7001e-16, 2.0874e-01, 9.9911e-01]]), array([[3.5620e-16, 4.2841e-01, 9.9942e-01]]), array([[0.    , 0.9999, 0.9989]], dtype=float32), array([[0.031 , 1.5152, 0.8681]]), array([[0.2866, 0.9399, 1.3832]]), array([[0.1289, 0.1888, 1.075 ]]), array([[4.6026e-16, 4.4031e-01, 9.9979e-01]], dtype=float32), array([[0.2397, 0.7745, 0.9773]]), array([[0.3603, 0.7835, 0.9992]]), array([[0.0927, 0.9704, 0.3847]]), array([[0.0292, 0.9992, 0.0693]]), array([[0.3669, 1.3028, 1.0076]]), array([[0.0441, 0.5622, 0.9734]]), array([[0.0746, 0.9964, 1.1769]]), array([[0.0036, 0.0347, 0.9997]]), array([[0.1953, 0.9857, 1.0221]]), array([[0.2239, 0.8783, 1.0286]]), array([[0.0632, 0.9463, 1.0496]]), array([[0.1565, 1.2723, 1.0619]]), array([[0.1226, 1.1816, 1.0474]]), array([[0.4109, 0.8148, 0.9988]]), array([[0.0536, 0.8876, 0.9056]])]'''

scales_numpy = np.stack(scales, 0).astype(np.float32)
scales_tensor = torch.tensor(scales, dtype = torch.float32)

scales_torch = scales_tensor[0]

print("scales_torch :\n", scales_torch)
print("scales_tensor[0] :\n", scales_tensor[0])

# for i in range(1, len(scales_tensor)):
#     temp = scales_tensor[i]
#     print("temp :\n", temp)
#     print("scales_torch :\n", scales_torch)
#     scales_torch = torch.stack((temp, scales_torch), dim = 0)
scales_tensor.view() # 9, 1,3


print("scales_numpy :\n", scales_numpy)
print("scales_numpy size :\n", scales_numpy.shape)
print("scales_torch :\n", scales_torch)
print("scales_torch size :\n", scales_torch.shape)


#print("scales_torch : ", scales_torch)

scales_torch :
 tensor([[0.0683, 0.9202, 1.0961]])
scales_tensor[0] :
 tensor([[0.0683, 0.9202, 1.0961]])
torch.Size([9, 1, 3])
scales_numpy :
 [[[0.0683 0.9202 1.0961]]

 [[0.4122 0.9997 0.7656]]

 [[0.1657 0.3025 0.9997]]

 [[0.0117 0.8207 0.653 ]]

 [[0.193  0.4365 1.0564]]

 [[0.0066 0.1864 0.9978]]

 [[0.1757 1.0406 0.7988]]

 [[0.0023 0.9993 0.0222]]

 [[0.0091 0.4855 1.0033]]]
scales_numpy size :
 (9, 1, 3)
scales_torch :
 tensor([[0.0683, 0.9202, 1.0961]])
scales_torch size :
 torch.Size([1, 3])
